#!/usr/bin/env node
// Mantrabe version management.
//
// Single source of truth: version.json — { major, minor, build }.
// Version is rendered as MAJOR.MINOR.BUILD (semver-ish; "build" is the
// patch component and auto-increments on every native build).
//
// Commands:
//   show               print current version (default)
//   bump build         increment build (default for `bump`)
//   bump minor         increment minor, reset build to 0
//   bump major         increment major, reset minor + build to 0
//   sync               rewrite all derived files at the current version
//                      without bumping (package.json, src/version.js,
//                      android/app/build.gradle, ios Info.plist)
//   release            sync, then create an annotated git tag v<MAJOR.MINOR.BUILD>
//                      pointing at HEAD
//
// versionCode (integer for Play Store / Apple) is computed as
//   major * 10000 + minor * 100 + build
// so 0.0.1 -> 1, 0.1.0 -> 100, 1.0.0 -> 10000. That stays monotonically
// increasing as long as minor and build never exceed 99 between major
// bumps, which is fine for any reasonable cadence.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const VERSION_FILE   = path.join(ROOT, 'version.json');
const PACKAGE_JSON   = path.join(ROOT, 'package.json');
const VERSION_TS     = path.join(ROOT, 'src', 'version.ts');
const ANDROID_GRADLE = path.join(ROOT, 'android', 'app', 'build.gradle');
const IOS_PLIST      = path.join(ROOT, 'ios', 'App', 'App', 'Info.plist');

function read() {
  if (!fs.existsSync(VERSION_FILE)) return { major: 0, minor: 0, build: 1 };
  return JSON.parse(fs.readFileSync(VERSION_FILE, 'utf8'));
}
function write(v) {
  fs.writeFileSync(VERSION_FILE, JSON.stringify(v, null, 2) + '\n');
}
const versionName = (v) => `${v.major}.${v.minor}.${v.build}`;
const versionCode = (v) => v.major * 10000 + v.minor * 100 + v.build;

function syncAll(v) {
  const name = versionName(v);
  const code = versionCode(v);
  const log = [];

  // package.json — used by electron-builder for desktop binaries.
  if (fs.existsSync(PACKAGE_JSON)) {
    const pkg = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
    if (pkg.version !== name) {
      pkg.version = name;
      fs.writeFileSync(PACKAGE_JSON, JSON.stringify(pkg, null, 2) + '\n');
      log.push('package.json');
    }
  }

  // src/version.ts — imported by the web UI so we can show the version.
  fs.mkdirSync(path.dirname(VERSION_TS), { recursive: true });
  const tsContent = `// Generated by scripts/version.cjs — do not edit by hand.\nexport const VERSION = '${name}';\nexport const VERSION_CODE = ${code};\n`;
  if (!fs.existsSync(VERSION_TS) || fs.readFileSync(VERSION_TS, 'utf8') !== tsContent) {
    fs.writeFileSync(VERSION_TS, tsContent);
    log.push('src/version.ts');
  }

  // Android build.gradle — versionName + versionCode.
  if (fs.existsSync(ANDROID_GRADLE)) {
    let g = fs.readFileSync(ANDROID_GRADLE, 'utf8');
    const before = g;
    g = g.replace(/versionCode\s+\d+/, `versionCode ${code}`);
    g = g.replace(/versionName\s+"[^"]*"/, `versionName "${name}"`);
    if (g !== before) {
      fs.writeFileSync(ANDROID_GRADLE, g);
      log.push('android/app/build.gradle');
    }
  }

  // iOS Info.plist — CFBundleShortVersionString + CFBundleVersion.
  if (fs.existsSync(IOS_PLIST)) {
    let p = fs.readFileSync(IOS_PLIST, 'utf8');
    const before = p;
    p = p.replace(
      /(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]*/,
      `$1${name}`,
    );
    p = p.replace(
      /(<key>CFBundleVersion<\/key>\s*<string>)[^<]*/,
      `$1${code}`,
    );
    if (p !== before) {
      fs.writeFileSync(IOS_PLIST, p);
      log.push('ios/App/App/Info.plist');
    }
  }

  return log;
}

function fail(msg) {
  console.error(msg);
  console.error('');
  console.error('Usage:');
  console.error('  node scripts/version.cjs show');
  console.error('  node scripts/version.cjs bump [build|minor|major]');
  console.error('  node scripts/version.cjs sync');
  console.error('  node scripts/version.cjs release');
  process.exit(1);
}

const cmd = process.argv[2] || 'show';
const v = read();

if (cmd === 'show') {
  console.log(`${versionName(v)} (versionCode ${versionCode(v)})`);
} else if (cmd === 'bump') {
  const which = process.argv[3] || 'build';
  if (which === 'build') {
    v.build += 1;
  } else if (which === 'minor') {
    v.minor += 1;
    v.build = 0;
  } else if (which === 'major') {
    v.major += 1;
    v.minor = 0;
    v.build = 0;
  } else {
    fail(`Unknown component: ${which}`);
  }
  write(v);
  const synced = syncAll(v);
  console.log(`Bumped ${which} -> ${versionName(v)} (versionCode ${versionCode(v)})`);
  if (synced.length) console.log(`Synced: ${synced.join(', ')}`);
} else if (cmd === 'sync') {
  const synced = syncAll(v);
  console.log(`At ${versionName(v)} (versionCode ${versionCode(v)})`);
  if (synced.length) console.log(`Synced: ${synced.join(', ')}`);
  else console.log('Already in sync.');
} else if (cmd === 'release') {
  const synced = syncAll(v);
  if (synced.length) {
    console.warn(`(synced ${synced.join(', ')} before tagging — review and commit if needed)`);
  }
  const tag = `v${versionName(v)}`;
  try {
    // Use --force-no-gpg-sign? No — let user's git config decide. Annotated tag.
    execSync(`git tag -a ${tag} -m "Release ${tag}"`, { cwd: ROOT, stdio: 'inherit' });
    console.log(`Created tag ${tag} at HEAD. Push with: git push origin ${tag}`);
  } catch (e) {
    console.error(`Failed to create tag ${tag}:`, e.message);
    process.exit(1);
  }
} else {
  fail(`Unknown command: ${cmd}`);
}
